### ISSUE TITLE
Jeknins Plugin Issue

### ISSUE THREAD

**Issue by anthonybe98** [Ma11hewThomas/matthew-thomas-backstage-plugins#10]
I'm trying to use the Jenkins plugin to create a job. I have This directory:
I have a seperate repository where I store all my templates
This is my template:
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-jenkins-job
  title: Simple Jenkins Job
  description: Template to create a simple Jenkins job
  tags:
    - example
    - jenkins
spec:
  owner: your-team-name
  type: service
  steps:
    - id: create-jenkins-job
      name: Create Jenkins Job
      action: jenkins:job:create
      input:
        configPath: ./content/config.xml
        jobName: example-project-build
        folderName: example-projects

I tired all the configPath I could think of. I did content/config.xml, I did the URL to my jenkins pipeline job config.xml, I tired removing content directory and did ./config.xml, I also did test/content/config.xml but nothing worked. All of them throw the same error:
ENOENT: no such file or directory, open './content/config.xml'

What is the correct way of doing it? Or is this a bug somewhere?
From readng the code, it seems like its a local path

![directory](https://github.com/Ma11hewThomas/matthew-thomas-backstage-plugins/assets/61373201/455656b3-90e7-47a9-acbd-9e638873759e)

**Comment by Ma11hewThomas** [comment]
As your templates are located in a separate repo, you might need to use the built in fetch:template action to retrieve the content/config.xml.

Please try this: 

``` yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
name: simple-jenkins-job
title: Simple Jenkins Job
description: Template to create a simple Jenkins job
tags:
- example
- jenkins
spec:
owner: your-team-name
type: service
steps:
    - id: template
      name: Fetch config
      action: fetch:template
      input:
        url: ./content
        targetPath: ./content
- id: create-jenkins-job
name: Create Jenkins Job
action: jenkins:job:create
input:
configPath: ./content/config.xml
jobName: example-project-build
folderName: example-projects
```

Let me know if this works.

**Comment by anthonybe98** [comment]
I updated the template to this:
```apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-jenkins-job
  title: Simple Jenkins Job
  description: Template to create a simple Jenkins job
  tags:
    - example
    - jenkins
spec:
  owner: your-team-name
  type: service
  steps:
    - id: template
      name: Fetch config
      action: fetch:template
      input:
        url: ./content
        targetPath: ./content
    - id: create-jenkins-job
      name: Create Jenkins Job
      action: jenkins:job:create
      input:
        configPath: ./content/config.xml
        jobName: example-project-build
        folderName: example-projects
```

this is my directory structure:
![image](https://github.com/Ma11hewThomas/matthew-thomas-backstage-plugins/assets/61373201/66b53cea-004c-4e58-8d76-f0a486546ef3)
And this is the error:
![image](https://github.com/Ma11hewThomas/matthew-thomas-backstage-plugins/assets/61373201/8ea3e76b-a45f-4a1d-9786-be9d9f639adb)

**Comment by Ma11hewThomas** [comment]
This should be fixed in version [0.2.6](https://www.npmjs.com/package/@ma11hewthomas/plugin-scaffolder-backend-module-jenkins/v/0.2.6)

``` yaml
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-jenkins-job
  title: Simple Jenkins Job
  description: Template to create a simple Jenkins job
  tags:
    - example
    - jenkins
spec: 
  owner: your-team-name
  type: service
  steps:
    - id: template
      name: Fetch config
      action: 'fetch:template'
      input:
        url: ./content
        targetPath: ./content
    - id: create-jenkins-job
      name: Create Jenkins Job
      action: 'jenkins:job:create'
      input:
        configPath: ./content/config.xml
        jobName: example-project-build
        folderName: example-projects
```
